### PR TITLE
Added on_mouse_wheel_move, implements #28

### PR DESCRIPTION
**Pull request by GreatGodOfFire**

### CODE REVIEW

**Comment by blaumeise20** [comment]
Thanks, this is what I was waiting for!

**Comment by QuantumBadger** [comment]
Thanks! This looks good on the glutin side, but currently needs an implementation for `WebCanvas` in `window_internal_web`. Would you like to add this @GreatGodOfFire? If not I'll take a look at it a bit later.

**Comment by GreatGodOfFire** [comment]
I am currently fixing it. I will run the formatter after that :)

**Comment by GreatGodOfFire** [comment]
Done

**Comment by QuantumBadger** [comment]
Great work, thank you! I'll probably rename the callback to `on_mouse_wheel_scroll()` just to make it clearer/easier to search for, but otherwise this looks perfect and I've merged it in.

**Pull request merged**
