### PR TITLE
Added window size getter to WindowHelper

### PR DESCRIPTION
**Pull request by dennisorlando**
The various structs have a lot of setters but lack many getters that would be very useful to use, like a get_pixel_size method to get the viewport size. 
This should address #76 

I also added a draw_rectangle_ref function because sometimes I want to keep my rectangle without moving it into draw_rectangle()

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thank you for this! I like the idea of being able to pass references to Rectangles but I think adding a `_ref` variant for each function is too messy. I've made the following change to instead accept `AsRef<Rectangle>` to these functions, which means you can pass either a `Rectangle`, or a `&Rectangle`. So the `_ref` part of the change can be removed.

It also looks like the file `test_basic_text_white_background_ACTUAL.png` has been accidentally committed?

Otherwise this looks good, thank you!

**Comment by dennisorlando** [comment]
Oh, I actually didn't know AsRef existed xD
It's definitely a valid and lovely solution.
I removed the _ref functions from the pull request and also that file that got somehow created, now only the get_size() remains

**Comment by dennisorlando** [comment]
Should I do something else to be able to merge or is this good to go? I'm kind of new to the open-source contributing stuff

**Comment by QuantumBadger** [comment]
Thank you, this mostly looks good to me! Sorry for the delay in responding, I normally review PRs within a week or two.

The CI has revealed a couple of issues:

* The formatting job is failing, which should be fixed by running `cargo fmt`
* The WebAssembly build is failing, it looks like the `get_bounding_client_rect` function doesn't exist.

It would be great if you could test the WASM version of this please -- there's a tutorial for how to do this [here](https://quantumbadger.com/2021/12/using-webgl-with-speedy2d.html).

Also it's fine if `cargo check` fails locally -- those tests only run correctly on Linux at the moment.

**Comment by dennisorlando** [comment]
Hmm I added a commit, I guess that only admins can run checks (?)

**Comment by dennisorlando** [comment]
image
Hmmm I see you've run checks; what kind of error is this, should I write a test function of some sort to use that function?

**Comment by QuantumBadger** [comment]
I think the issue is that the function (in `web.rs`) needs to be tagged with `#[cfg(feature = "windowing")]`, as it's only used when that feature is enabled.

**Comment by dennisorlando** [comment]
*sigh* sorry for the trouble xD

**Comment by QuantumBadger** [comment]
No worries! Looks like it's all building now.

Thanks again for submitting this -- I'll get it merged in shortly.

**Comment by QuantumBadger** [comment]
Merged and changelog updated. Thanks again!

**Pull request merged**
