### PR TITLE
Add example of managing GL context using glutin

### PR DESCRIPTION
**Pull request by btbaggin**
Added a minimal example showing how to manage a GL context yourself, using glutin for windowing.
Tested on Windows and Linux

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thanks for this @btbaggin! I should hopefully get a chance to review this within the next week.

**Comment by QuantumBadger** [comment]
I think the Clippy failure isn't your fault -- I'll fix this when I review the code.

**Comment by QuantumBadger** [comment]
Thank you, this looks good! Sorry for the delay in reviewing.

Before I merge this, please could you add (1) the standard copyright header comment (you can copy this from another file), and (2) a comment at the top of the file explaining what the example is showing (i.e. how to manually manage the GL context yourself using Glutin). Thanks again for this!

**Comment by btbaggin** [comment]
Done! Sorry it look a while. I don't come around here often.

I had the code lying around so I figure I should give back. Your library has been super helpful in my personal projects.

**Comment by QuantumBadger** [comment]
Thank you! I'll merge this in.

**Comment by QuantumBadger** [comment]
Changelog updated here: https://github.com/QuantumBadger/Speedy2D/commit/ad28244c8591d94c4285127e15d9cdedb382e7d1

Thanks again!

**Pull request merged**
