### PR TITLE
generalise UserEventSender: Clone

### LINKED ISSUE #94: UserEventSender: Clone should not require T to be clone
https://docs.rs/speedy2d/1.12.0/src/speedy2d/window.rs.html#55

I don't know how it works interanlly, but istm that Clone should be implemnted even if the underlying event isn't clone

### PR DESCRIPTION
**Pull request by matklad**
closes #94

### CODE REVIEW

**Comment by matklad** [comment]
image


FYI:

https://matklad.github.io/2022/10/24/actions-permissions.html

**Comment by QuantumBadger** [comment]
Thank you! This makes sense and I'm happy to merge after the checks have run.

**Comment by QuantumBadger** [comment]
The failures are probably related to the ones on `master`, I'll get those fixed and will rebase this.

**Comment by QuantumBadger** [comment]
Merged and changelog updated. Thanks again!

**Pull request merged**
