### PR TITLE
Added with_fixed_resolution option to WindowCreationOptions

### PR DESCRIPTION
**Pull request by superlou**
This is a draft to address #86. I am sure there is a better way, but this is a basic example of what I'm trying to do.

### CODE REVIEW

**Comment by superlou** [comment]
I updated the window creation option to instead be `with_fixed_resolution` to more accurately capture the intent. I also added a `set_resolution` function on `Graphics2D` that can be used to dynamically set the resolution during `on_draw`.

**Comment by QuantumBadger** [comment]
Thanks for submitting this, and sorry for the big delay in looking at it -- I'm aiming to review this soon.

**Comment by superlou** [comment]
No worries! I'm not really sure it's in any state for a review. I made some pretty hacky changes because I'm not sure I really understand the architecture. Consider it a _very_ rough draft and I'm open to suggestions.

**Comment by superlou** [comment]
Do you think a possible 2.0 API would affect this?

**Comment by superlou** [comment]
@QuantumBadger, I've been using this for a bit and I haven't run into any issues. Would it be possible for you to take a look and see if there is anything I should address?

**Comment by QuantumBadger** [comment]
Sorry for the delay, I've been quite busy over the last few weeks. Thank you again for doing this!

It seems pretty reasonable, however I think it would be more useful if:

* The aspect ratio was maintained (e.g. centering the image and adding black bars at the edge of the screen)
* Text was drawn at high quality, or at least was consistent with shapes -- currently shapes are drawn at full resolution, whereas text is rendered at the low resolution and then drawn with nearest neighbor scaling (which looks pretty bad).

The `fixed_resolution` naming could be a bit misleading as the resolution changes with the window size, and the viewport is the thing that gets scaled (hence why circles/etc are drawn with high quality).

There are a couple of alternatives to this approach:

* To draw everything at a low resolution and scale up, it's possible to draw to a texture, and then render that texture to the screen (scaled up).
* To draw everything at a high resolution, it may be best to scale everything on the API side rather than the OpenGL side, e.g. by scaling up all the coordinates passed in by the user. However text still presents a problem here as the size is needed at the layout step, rather than the draw step, so we'd need to add a second text scale to `RenderQueueItem`.
  * It would make sense to implement this as a sort of "wrapper" for the API if possible, to eliminate any overhead for most users. I.e. you'd have a struct like `ScaledGraphics2D`, which has a reference to a `Graphics2D` internally, and scales the user's coordinates before passing them to `Graphics2D`.

Hopefully all that makes sense! I'm happy to answer any questions and clarify more if needed.

**Comment by superlou** [comment]
No worries about any delay! I've been swamped by my day job, so I'm moving pretty slow on this, too. I appreciate your help!

Taking a step back, I think if I explain my use case, it might help understand my (admittedly poor) naming for the feature. I'm trying to provide a Javascript API for digital signage "applications," which provides simplified drawing commands run every frame. The end result is something like this work-in-progress example:

https://github.com/superlou/signrs/tree/main/examples/app2

https://github.com/superlou/signrs/assets/709695/9efa7d1f-9efe-4683-b5d3-db6a524a9ad2

In the applications, it is more like a game viewport than a resizable desktop application viewport, where designing at a lower resolution is for performance. My goal is to be able to run that example application above at 60 FPS on a Raspberry Pi 3 (as well as cross-platform on desktops).

The application is run full-screen all the time when in normal use; however, when developing the custom Javascript applications on a desktop, it's convenient to have them scaled down. I think scaling with black bars might be ok, but in production, it would often be better to have some minor stretching than show black bars (though maybe that should be configurable).

I didn't realize the hack I had done was still drawing shapes at full resolution. I had expected the text to be lower quality since I thought I was doing something like your first approach: drawing at lower resolution and scaling up. That's why I thought I was drawing at a fixed (maybe virtual?) resolution that was then scaled up to the window's resolution.

So, I like the idea of a flag to decide if the aspect ratio is maintained, and I think I'm looking to draw at low resolution and scale up. That said, if that isn't actually a performance improvement, then I'm going down the wrong path.

**Comment by superlou** [comment]
Sorry to bump this, but any thoughts on this use case and if there was a better path I should explore in this PR? I tried a Raspberry Pi 4 hoping that would make this a non-issue, but text rendering is still my bottleneck.

**Comment by QuantumBadger** [comment]
Rendering to a low-res texture and scaling up is one alternative as mentioned above, although the GPU is still going to be working hard to fill all 1920x1080 pixels every frame.

Just some thoughts:

* Is it possible to turn down the Raspberry Pi's display resolution to e.g. 720p?
* I assume that multisampling is set to 1 as you mentioned in #83.
* Are you building your app in release mode (`--release`) or the default debug mode? This can have a big impact on text rendering performance
* The scrolling text on the bottom should be restricted to integer positions for performance. If the decimal component of the position changes, then the text needs to be regenerated. If this is kept the same (which is easiest to ensure by just rounding to the nearest int), then Speedy2D caches each character as an image for fast drawing.

**Comment by superlou** [comment]
> Is it possible to turn down the Raspberry Pi's display resolution to e.g. 720p?

<slams hand into farhead> I should've thought of that a long time ago. Drawing to a low-res texture and scaling up still sounds like a feature I want so that when I'm developing on a PC, I can resize the window, but I am going to try changing the Raspberry Pi resolution as soon as I get back from work travel.

Is drawing to a low-res texture and scaling something that has to be done with a custom context, or is that something that can be done with the built-in window handler?

> I assume that multisampling is set to 1 as you mentioned in
https://github.com/QuantumBadger/Speedy2D/issues/83.
> Are you building your app in release mode (--release) or the default debug mode? This can have a big impact on text rendering performance

Yes for both of these. Running in release is definitely a huge difference vs. debug.

> The scrolling text on the bottom should be restricted to integer positions for performance. If the decimal component of the position changes, then the text needs to be regenerated. If this is kept the same (which is easiest to ensure by just rounding to the nearest int), then Speedy2D caches each character as an image for fast drawing.

I didn't realize that (and I see it now looking at the documentation). I added it to my app and will try it ASAP on the RPi. On a tangent, if round returns a Vector2D that still has elements of f32, how can you tell that the positions are exactly integers given floating point quantization?

**Comment by QuantumBadger** [comment]
> Is drawing to a low-res texture and scaling something that has to be done with a custom context, or is that something that can be done with the built-in window handler?

Drawing to textures is currently unsupported, but it would be great to add this as a feature!

> how can you tell that the positions are exactly integers given floating point quantization?

Integers up to `2^23` can be represented exactly as floats, by making use of the 23 bits in the mantissa, so simply calling `round()` should be fine.

For the purposes of caching, Speedy2D uses buckets of 0.1 x 0.1 pixels, giving 100 (`10 * 10`) possible subpixel positions for each glyph -- so we still cache for non-integer values, but you're just less likely to have a cache hit.

**Comment by superlou** [comment]
> Drawing to textures is currently unsupported, but it would be great to add this as a feature!

Do you think this should be exposed as a stateful Graphics2D feature like `.set_clip`, where you set the current texture to draw to, and subsequent commands draw to the texture? Or would you create a texture that implements most of the methods of Graphics2D?

I think either one would be enough to then let the user draw the texture, scaled to the screen with the normal graphics context. Either approach may be more flexible than how I initially envisioned this PR, where it was a configuration of the window.

**Comment by superlou** [comment]
I finally got a chance to try running with the rounded text positions, and that definitely seems to help. It's nearly 60 fps now, but still dips down for text heavy draws. Changing the raspberry pi resolution to 1280x720 definitely makes it hold 60 fps, though I guess that's counting on the TV to do the scaling? Do you have any thoughts on how a Texture2D API would look?

**Comment by QuantumBadger** [comment]
Glad it's improved now! Yes the TV would do the scaling in that case.

> Do you have any thoughts on how a Texture2D API would look?

Ideally something like this, inside `Graphics2D`:

```rust
pub fn draw_to_image(
    &mut self,
    image: &ImageHandle,
    operations: FnOnce(&mut Graphics2D)
)
```

So to draw a rectangle to an image, you'd call it as follows (in `on_draw()`):

```rust
graphics.draw_to_image(&image, |graphics| {
    graphics.draw_rectangle(...);
});
```

The operations done in the closure would apply to the image, rather than the main window.

**Pull request closed without merging**
