### PR TITLE
Added polygon drawing support.

### PR DESCRIPTION
**Pull request by chilipepperhott**
I assume the reason this library does not already accept drawing polygons is because it requires triangulation. I had a shot a remedying that. I will admit my knowledge of the inner workings of the library are sketchy at best, and my implementation is not ideal, especially in performance, but I figure anything is better than nothing.

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thank you, this looks good! To fix the CI the formatter needs to be run in nightly mode:

```
rustup toolchain install nightly
cargo +nightly fmt
```

Regarding performance, I think it would be good to split up the triangulation step from the drawing step, so the expensive triangulation doesn't need to be done every frame. For example:

```rust
let my_polygon = Polygon::new(&[
        Vector2::new(0.0, 0.0),
        Vector2::new(1.0, 0.0),
        Vector2::new(0.0, 1.0)
]);

graphics.draw_polygon((100.0, 200.0), &my_polygon, Color::BLUE);
```

The triangulation would be done inside `Polygon::new()` -- that way `draw_polygon()` can simply append the already-generated triangles to the render queue.

Also just a minor note, the docs are slightly ambiguous about the order in which the vertices need to be provided. They presumably do need to be provided either clockwise or counter-clockwise, otherwise sets of vertices for certain concave shapes would have multiple possible renderings (e.g. think of a concave pentagon, with four vertices arranged in a square, and the fifth in the middle). It might be best for the docs to restrict this to "clockwise" for future-proofing, and consistency with `draw_triangle()`.

Otherwise this is great, so thanks for submitting this!

**Comment by chilipepperhott** [comment]
Thanks for the feedback! Sorry about that formatting issue, I had a brain fart there. 

About the order of vertices. `earcutr` will output the same triangulation if the input is reversed. But I think that I understand your point is that Speed2D might change to something else in the future, which may not have the same property.

I made the changes you outlined for performance. I wasn't sure what the most user friendly way of allowing for coloring of vertices was, and it didn't look quite right before, so I removed that bit. Let me know your thoughts!

**Comment by QuantumBadger** [comment]
Perfect, thank you! I'll aim to get this merged in within the next week.

> About the order of vertices. earcutr will output the same triangulation if the input is reversed

Ah sorry, I just meant that if the vertices were in a totally random order it wouldn't work -- `12345` and `54321` should be fine, but `13524` for example would produce something weird. So a comment along the lines of "either clockwise or counter-clockwise" might be less ambiguous than "any order".

Regarding limiting it to clockwise only, after thinking about it some more, I guess people are going to unknowingly rely on the "either way" behaviour -- if we change that in future it could break that existing code, which I'd like to avoid even if the user is defying the docs :smile: So it may actually be best to say both orders are acceptable, and we'll stick to that contract in future.

> I wasn't sure what the most user friendly way of allowing for coloring of vertices was, and it didn't look quite right before, so I removed that bit. Let me know your thoughts!

Yeah, that's a good point. Perhaps the `Polygon` struct could also store the corresponding input vertex IDs along with the triangle vertices, which would allow the user to pass in a `&[Color]` to `draw_polygon_vertex_colors()` like before.

**Comment by QuantumBadger** [comment]
Thanks again! I've made some changes to this and have released v1.5.0.

**Pull request merged**
