### PR TITLE
added RoundedRectangle with Rectangle integrations

### PR DESCRIPTION
**Pull request by dennisorlando**
- referred by #81

### CODE REVIEW

**Comment by dennisorlando** [comment]
@QuantumBadger should be good to go

**Comment by QuantumBadger** [comment]
Thank you for this, I've taken a look and it looks great. I'll get this merged in shortly -- sorry for the delay in reviewing!

**Comment by dennisorlando** [comment]
Hey again, is this pull request good to go? Had to shift my focus to other things, sorry!

**Comment by QuantumBadger** [comment]
Ah sorry, this slipped my mind -- I'll aim to look at this again within the next few days.

**Comment by QuantumBadger** [comment]
Thanks again for this @dennisorlando! I've added some tests, updated the changelog, and merged this in. Apologies again for the delay!

**Pull request merged**
