### PR TITLE
Improve Vectors

### PR DESCRIPTION
**Pull request by InfiniteCoder01**
+ Vec2 Default
+ From<T>
+ Mul & Div same as Add & Sub

### CODE REVIEW

**Comment by QuantumBadger** [comment]
Thank you for this!

* Adding `Default` for `Vec2` is reasonable, although we do already have `Vec2::ZERO` which is a bit more explicit.
* Implementing `From<T>` for `Vec2<T>` seems a bit confusing -- it's probably not that common for users to create a 45 degree vector from a scalar where `x = y`. Is there a use case for this?
* Similarly the implementations of `Vec2 * Vec2` and `Vec2 / Vec2` don't make sense mathematically -- I'd expect either the cross product or dot product for `*`, and in either of those cases, they should be in named methods to make it clear which one they're using. Is there a use case for `(x1 * x2, y1 * y2)`?

**Comment by InfiniteCoder01** [comment]
Thanks for reviewing my PR!

- Yes, `Vector2::ZERO` is more explicit than default. But it stops us from `#[derive(Default)]` on structs that contain vectors
- Implementing `From<T> for Vector2<T>` is useful when we want to to add a scalar to vector or multiply a vector by a scalar.
- Multiplying vectors together is useful when we want to get texture coordinates of a tile when we know tile size. We can use vector division if we want to get normalized UV coordinates when we know texture coordinates and texture size.

Those aren't all use cases, but I hope this makes it clear.

**Comment by QuantumBadger** [comment]
Thank you, and sorry for not looking at this in a while!

I can definitely see the use cases for these, although I think because these operations are mathematically ambiguous, it would be better for them to be implemented in the user's app, if they have this specific use case.

Generally I prefer explicit stuff to implicit -- in the case of scalar to vector conversion, or vector multiplication, there are several ways of doing that which make sense, but should be explicitly named.

**Comment by InfiniteCoder01** [comment]
Unfortunately, rust doesn't allow implementing traits like Mul/Div (or any foreign traits) on foreign types. Perhaps, this could be a feature?

**Comment by QuantumBadger** [comment]
@InfiniteCoder01 That's a good point, however I think it would be confusing to have the library's build features define how multiplication is implemented. Multiplication on vectors typically involves the cross product or the dot product, whereas the operation implemented in this PR is (AFAIK) known as the Hadamard product.

I'd accept a PR for an explicitly named + documented function, e.g. `mul_components()` as in the `vector2d` crate.

**Pull request closed without merging**
